### ISSUE TITLE
Need a little help (pywal)

### ISSUE THREAD

**Issue by vaskark** [oncomouse/lushwal.nvim#3]
I have the following in my colorscheme.lua file (called from init.lua):

```
vim.cmd([[colorscheme lushwal]])
vim.g.lushwal_configuration = {
	addons = {
               ...
		ale = false,
               ...
	},
}

require("lushwal").add_reload_hook({
	vim.cmd("LushwalCompile"),
})
```

And it works ok. I'm just wondering if I can move some of this into my lushwal.lua plugin file (like the config table). I've several times but can't quite get it to work.

Any help would be greatly appreciated.
Thanks.

Edit: Seems I can move the vim.g.lushwal_configuration table into my lushwal.lua (inside a config = function() ... end, structure). And the add_reload_hook is all that's needed for this to work in colorscheme.lua.

Is this the correct way?

**Comment by oncomouse** [comment]
I'm assuming you're using LazyVim for your plugin manager, so if not, this won't work, but you could configure the above as:

~~~ lua
return {
  "oncomouse/lushwal.nvim",
  init = function()
    vim.g.lushwal_configuration = {
      addons = {
        ...
        ale = false,
        ...
      },
    }
  end,
  config = function()
    require("lushwal").add_reload_hook({
      vim.cmd("LushwalCompile")
    })
  end,
  cmd="LushwalCompile",
}
~~~

I don't think it matters too much, but `vim.g.lushwal_configuration` should be done in an `init()` rather than a `config()` to be set before lushwal is first required.

Hope that helps.
